import Pkg
Pkg.add("FLAC")
Pkg.add("DSP")
Pkg.add("DiffEqFlux")
Pkg.add("DifferentialEquations")
Pkg.add("FFTW")
Pkg.add("FLAC")
Pkg.add("FileIO")
Pkg.add("Flux")
Pkg.add("IJulia")
Pkg.add("IterTools")
Pkg.add("JLD")
Pkg.add("Plots")
Pkg.add("WAV")